### ISSUE TITLE
Add A Version for VS2022

### ISSUE THREAD

**Issue by Captain-Quack** [Rickaym/manim-sideview#100]
This is a great extension! Could it be available for Visual Studio as well?

**Comment by Rickaym** [comment]
Hey,

I'm not sure what the process would be like. Are you familiar with Visual Studio plugins? And what's the size of the python community like on VS?

**Comment by lbirkert** [comment]
This would require a rewrite in the C# language, which'd be tedious. We might find a way to write a C# wrapper that spawns a node process, which then has access to the C# APIs, but still, the APIs are completely different.

**Comment by lbirkert** [comment]
Why would you want to use Manim on Visual Studio though and why is installing VS Code not an option here?
