### ISSUE TITLE
Better handling of output video folders withouth having to resort to an external config.cfg file

### ISSUE THREAD

**Issue by e-dervieux** [Rickaym/manim-sideview#102]
I spent quite some time not understanding what was happening after I added the `-qm` option for medium quality into the sideview's manim CLI arg field (`manim-sideview.commandLineArgs`). Indeed, the compilation went well, but visualisation failed with the following error message:
```
Manim Sideview: Predicted output file does not exist at "/.../src/media/videos/dlr/1080p60/myvideo.mp4" Make sure that the designated video directories are reflected in the extension log.
```
I understood what happened by looking at the compilation output which said:
```
File ready at '/.../src/media/videos/dlr/720p30/myvideo.mp4'   
```
Apparently, sideview did not take into account the impact of the change in quality on the output file path and still looks for a 1080p / 60fps (*i.e.* high quality) video, while the actual one is 720p / 30fps (*i.e.* low quality) video.

----

I later noticed that this was documented with a **Warning** in the project's `README` but I feel that this could be improved in some ways:
  - Because few people read the `README`s past "getting started" (it's a caricature, of course, but mainly sad but true)
  - Even if we read this `README` at some point, we can forget it by the time the error occurs, so I think that the warning message could be put **directly into** sideview's CLI args setting, as a reminder. Something like:
![image](https://github.com/user-attachments/assets/dbdfd416-95e4-471a-9840-bf623472a849)
  - This whole issue could also be solved by having sideview look into manim's console output and take the file path given in the `File ready at` line to preview it.

**Comment by Rickaym** [comment]
Thank you for raising this issue. Let's continue this discussion on the pre-existing issue #99
