### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by Enderh5** [Rickaym/manim-sideview#15]
Hi,
First of all, I love the extension, it makes using manim so much easier.
I've only had two issues,
Is there any kind of preview for images, because I'm using manim to make diagrams for my class notes and it would be useful. And also I use a square aspect ratio for said images and that has also caused issues, even when making a video.

**Comment by Rickaym** [comment]
Hey Ender, I'm glad you've found this useful. I'll b3 rolling out the image preview addon for the next update. For the square aspect ratio problem, could you perhaps provide some screenshots of what's gone wrong?

**Comment by Enderh5** [comment]
So when I tried to make a video with a square aspect ratio it cropped it in the preview and I couldn't see the entire image, but I have tried it now and it seems to not happen anymore. It may have been an issue with my code or my config. 
Sorry for the inconvenience.

**Comment by Rickaym** [comment]
> So when I tried to make a video with a square aspect ratio it cropped it in the preview and I couldn't see the entire image, but I have tried it now and it seems to not happen anymore. It may have been an issue with my code or my config. 
> Sorry for the inconvenience.

No worries, I'll mark this issue as soon feature request for picture display.

**Comment by Rickaym** [comment]
Implemented and closed by master@85a7871
