### ISSUE TITLE
Can original manim be supported?

### ISSUE THREAD

**Issue by IcyChlorine** [Rickaym/Manim-Sideview#18]
The current extension works for manim CE(community version).
Is it possible to tailor it so that it also works for original manim ver.(gl ver. by Grant)?
I would really appreciate it if the author can do it. XD

**Comment by Rickaym** [comment]
Hey IcyChlorine,

I have not previously considered this but if there is such a need. 
As I haven't really used Grant's version before, I'll have a look into it and keep the updates posted
in this issue.

Thank you for the suggestion!

**Comment by kolibril13** [comment]
Hey IcyChlorine,
Grant's version of manim is a personal project, and he quickly iterates on it.
The community version is a more stable version, and therefore a gallery like this would need to be regularly updated to his latest version. Therefore, I think it's not worth the effort to create such a gallery for his version.
