### ISSUE TITLE
Multiple command line args

### ISSUE THREAD

**Issue by ksthicke** [Rickaym/manim-sideview#19]
If you go into the Manim Sideview setting in VScode and try to set two command line args, it will error out.  This seems to be because the command line args are put in quotes when the command is executed.  A dirty workaround is to put quotes in between the arguments.  For example:
doesn't work: --disable_caching -ql
does work: --disable_caching" "-ql

I'm not sure if there was a reason for putting the command line args in quotes.  If there is not a good reason for it, then I guess this should be a simple issue to fix.

**Comment by Rickaym** [comment]
Noted, I'll see to this issue--if it indeed is the quotes that are the problem, they're already removed and the effects will take in by 0.0.14, which is our next major release!

Thanks,
Ricky.
