### ISSUE TITLE
You need a valid Python file to run the sideview?

### ISSUE THREAD

**Issue by carveybunt** [Rickaym/manim-sideview#23]
Why I get the error You need a valid Python file to run the sideview,. I installed the manim already.

mac: 12.5
python: 3.8

**Comment by Rickaym** [comment]
This usually happens when you try to run manim-sideview without a Python file opened as an active editor. 

Make sure to select your python, and then press the run.

With Regards,
Ricky.

**Comment by carveybunt** [comment]
@Rickaym Thanks, but I still don't get it. I already created a file of python:
```py
from manim import *

class SquareAndCircle(Scene):
    def construct(self):
        text = Text("test")
        self.play(write(text))
        self.wait(3)
```

**Comment by Rickaym** [comment]
Your code looks fine, can you please tell me how you're running the file?

With Regards,
Ricky.

**Comment by carveybunt** [comment]
Thank you very much again.

My vscode setting：
![截屏2022-08-17 19 54 30](https://user-images.githubusercontent.com/37894474/185112287-55546277-c43f-48a5-be6a-0969ad6cc63d.png)

My code file:
![截屏2022-08-17 19 57 20](https://user-images.githubusercontent.com/37894474/185112782-3fe89b6a-f309-4897-8361-05eafd43322f.png)

I ran the file by the following method:
![截屏2022-08-17 19 57 55](https://user-images.githubusercontent.com/37894474/185113053-ffce1115-71a1-44cb-8f5c-c06156fb947b.png)

Nothing happened when I click `SquareAndCircle`.

At the times, I got the error `ModuleNotFoundError: No module named 'manim'` when I run python file by the following method:
![截屏2022-08-17 20 05 46](https://user-images.githubusercontent.com/37894474/185114240-2efdc526-7669-4fd4-b10c-4df4f7b4dec4.png)

**Comment by Rickaym** [comment]
Ah. I see. Does calling `manim` in your terminal function properly?

One alternative is to try specifying the direct location to the manim executable like down below:
![image](https://user-images.githubusercontent.com/66440980/185116938-ec97d28d-e2d2-4bc0-9363-e1e0351d2b36.png)

I'm not sure where the executable is stored on MacOS but it should be somewhere inside `/Users/carveybunt/Library/Python/3.8/`

No problem!
Ricky.

**Comment by carveybunt** [comment]
Thanks again, I solved the problem.
My absolute path to the manim executable is `/Users/carveybunt/Library/Python/3.8/bin/manim`.
It working now, but the plugins threw the error `Hey! You need a valid Python file to run the sideview.`. This is a bug?
In fact, I have set it like this, but because of this error, I did not execute the file.

**Comment by Rickaym** [comment]
Before it threw the error, does it allow you to pick a scene name? 
Could you also please provide a log for the manim terminal output (see screenshot below)?

I'm unable to recreate the issue on my end: 
![image](https://user-images.githubusercontent.com/66440980/185131679-52891ffc-f598-48d2-b730-f56a70adcd06.png)

Ricky.

**Comment by carveybunt** [comment]
Since I had the error,  I thought this wrong path so I never picked any scene name.  But the path is right.

**Comment by Rickaym** [comment]
> Since I had the error, I thought this wrong path so I never picked any scene name. But the path is right.

Right, does it work when you pick a scene name? If it doesn't, could you please show me the log as previously requested?

Ricky.

**Comment by carveybunt** [comment]
It's working now, thanks again. I will close this issue now.
![截屏2022-08-17 20 58 10](https://user-images.githubusercontent.com/37894474/185140062-5e56462e-5e70-48c0-8cba-ec2d7ae80db9.png)

**Comment by Rickaym** [comment]
No Problem.
Ricky.
