### ISSUE TITLE
How can I change to another class?

### ISSUE THREAD

**Issue by carveybunt** [Rickaym/manim-sideview#24]
First of all, thanks for your plugins. But I had some problems: I had more classes in my code python,  how can I change classes `runs a Sideview` after I already ran a class?

My code:
```py
from manim import *

class SquareAndCircle(Scene):
    def construct(self):...

class SinAndCosFunctionPlot(Scene):
    def construct(self):...
```

I had two choices when I ran the first time, but I can't choices again when I want to change to another class because I can't see any option when I clicked the icon by `runs a Sideview`.
![截屏2022-08-24 16 22 19](https://user-images.githubusercontent.com/37894474/186368375-e7623448-dd2d-4367-b0f0-cebf5b851a87.png)

**Comment by Rickaym** [comment]
Please take a look at the issue below.

#17 

- Ricky

**Comment by carveybunt** [comment]
> Please take a look at this issue #17
> 
> * Ricky

I get it, thanks again.
