### ISSUE TITLE
Settings for using a custom external video player.

### ISSUE THREAD

**Issue by Aurora2500** [Rickaym/manim-sideview#26]
I came across needing to seek or rewind a video in the playback, but as it was said in #7, this seems to be a limitation on VSCode's part.

I figured that a neat alternative to it could be to give it a setting to run a command against the file itself. This way, upon saving my scenes, the extension can just open my own video player that doesn't need to adhere to Code's limitations.

So for example, I could set it as `mpv --loop`, and this would mean that when I save my scene, it would open it with `mpv --loop path/to/video.mp4` & I could see it with mpv where I can seek trough it and so on.

**Comment by Rickaym** [comment]
Great idea, I can work on this as part of the 0.1.5 release :)
I've also been working on trying to connect the extension with an external media player (specifically the VLC media player) as part of the release--this feature request seems easier to integrate and useful.

Ricky.

**Comment by Rickaym** [comment]
Hi @Aurora2500 
Please look at https://github.com/Rickaym/manim-sideview#3-how-do-i-execute-a-command-after-the-rendering-is-done on how to do this.

Ricky.
