### ISSUE TITLE
Output path stuck at 1080p60

### ISSUE THREAD

**Issue by AaronShelby** [Rickaym/manim-sideview#31]
When I change the render quality (in the file with config.quality = "..._quality") to other than "high_quality", there's no output and an error saying that no file is in the 1080p60 folder, which is normal.

**Comment by Rickaym** [comment]
Which file did you change the option in?

**Comment by AaronShelby** [comment]
I meant the python file, where the code is.

**Comment by Rickaym** [comment]
Ah, yes, the extension does not look into options set in the source code, rather, if you want the extension to realize the change, you should use an external `manim.cfg` file.

**Comment by AaronShelby** [comment]
well, thank you for the quick fix, as easy as it seems to be
