### ISSUE TITLE
 "Check for Updates" button in Manimsideview won't work with latest mobject gallery version

### ISSUE THREAD

**Issue by kolibril13** [Rickaym/manim-sideview#32]
I just updated all plywood galleries to the latest version (https://github.com/kolibril13/plywood-gallery/issues/24), including the [mobject gallery](https://kolibril13.github.io/mobject-gallery/), which has now the latest plywood infrastructure:

https://github.com/kolibril13/mobject-gallery/blob/04a50f43acccdf548c5bbf18304d417bfa0e56a9/gallery_assets/gallery_parameters.json#L1-L12

That means, that the "Check for Updates" button in Manimsideview won't work any more.
The plywood gallery extension and the manim sideview extension are now 100% equivalent, so maybe it would be even possible to deprecate the manim sideview gallery feature and link people to the plywood gallery extension. But I guess it also won't hurt to simply keep it in the sideview repo.

**Comment by kolibril13** [comment]
Another comment:
Since this latest mobject gallery version, I remove indentation manually on the front end like this:

https://github.com/kolibril13/mobject-gallery/blob/f41ac0a876f2b87ba081a23283bd1185371c1daf/index.html#L436-L438

It was the easiest solution and it works fine. But on the long run, I think the indentation correction should happen in the plywood backend, so that the json file can be used as it is.

**Comment by KekOnTheWorld** [comment]
> The plywood gallery extension and the manim sideview extension are now 100% equivalent, so maybe it would be even possible to deprecate the manim sideview gallery feature and link people to the plywood gallery extension.

As far as i remember, this was already planned for when plywood gets stable enough.
