### ISSUE TITLE
Questions about how to turn on ManimSV Stop

### ISSUE THREAD

**Issue by liujiangmu** [Rickaym/manim-sideview#33]
Hello Dear author, I am a beginner in manim, thank you for making such a good plugin for manim. But I have some problems when I download and use it. When I use it for the first time, ManimSV is on in the red part in the picture below, but when I use it again, ManimSV is not on, it looks like it is stopped, and then the test code is not displayed in the side pane. How can I solve this problem, thank you very much for your reply. This problem has been bothering me for a long time.

![image](https://user-images.githubusercontent.com/70685608/216924418-5628c596-f91b-4165-b239-406bf2af0534.png)

**Comment by Rickaym** [comment]
Hey,

If you want to re-run the render, you can press the run button again or execute the run command.
But it seems like you're having an issue. Can you please check if your manim exe is properly installed? And that it is on PATH, i.e., when typing `manim` into CMD/PS the manim CLI menu is brought up. 

If the extension is at a custom path, you will need to configure the option here to the path: https://github.com/Rickaym/manim-sideview#2-how-do-i-change-the-default-manim-executable-path

**Comment by Indian-otaku** [comment]
Did ya solve the problem? I'm facing the same problem. 
Also as mentioned by @Rickaym I set manim.exe in PATH.

**Comment by Indian-otaku** [comment]
Actually wait after pasting the same path to custom path it works but now there is another type of error. Thanks @Rickaym @liujiangmu 

New error: 
![image](https://user-images.githubusercontent.com/84381682/232950381-afce7b74-6deb-44c5-951d-bedd86064fd3.png)

**Comment by Rickaym** [comment]
> Actually wait after pasting the same path to custom path it works but now there is another type of error. Thanks @Rickaym @liujiangmu
> 
> New error: ![image](https://user-images.githubusercontent.com/84381682/232950381-afce7b74-6deb-44c5-951d-bedd86064fd3.png)

I believe this is the same issue as your comment [here](https://github.com/Rickaym/manim-sideview/issues/45#issuecomment-1514055814).
