### ISSUE TITLE
`Manim Sideview: Unable to infer the file-type for "xxx". Please select below.` Always pops up

### ISSUE THREAD

**Issue by DanielHabenicht** [Rickaym/manim-sideview#59]
I keep on getting this popup on every save:
![image](https://user-images.githubusercontent.com/13590797/227481670-147f67c7-34a0-41a5-a9cb-2e0b34cfcff7.png)

It results in rendering this extension useless because now instead of just saving and looking at the output I have to click the message each time. 

Is there any workaround? 
Or maybe it can save the decision for the current session?
Or it would be really neat if an open Preview tab would autorefresh if it detects that the file it is previewing has changed. 
Thanks, otherwise it really works well!
Might there be the option to use the PIP View without having the preview pane open?

**Comment by KekOnTheWorld** [comment]
Could you please provide the source code of the file you are trying to render?

**Comment by Rickaym** [comment]
Could you please explain what you mean by this? 

> Or it would be really neat if an open Preview tab would autorefresh if it detects that the file it is previewing has changed.

The preview should automatically reload once a new scene is rendered.

**Comment by Rickaym** [comment]
Updating to `0.2.4` should fix the issue.

**Comment by Rickaym** [comment]
> Thanks for the update! I will try it out later today.
> 
> > Could you please explain what you mean by this?
> > > Or it would be really neat if an open Preview tab would autorefresh if it detects that the file it is previewing has changed.
> > 
> > 
> > The preview should automatically reload once a new scene is rendered.
> 
> That would have been another way of updating the current sideview. I think currently it is updated as soon as the scene is rendered (basically as the command is finisehd). Another way would be to listen to file changes of the MP4 or image file and then reload. Thus updating the sideview even if one is running the manim command manually. But thats not really needed, as you fixed this bug.

Ah understood. No worries! Thanks for reporting the issue.

**Comment by Rickaym** [comment]
With regards to:
> Might there be the option to use the PIP View without having the preview pane open?
we do have #26

**Comment by jpvanoosten** [comment]
I have Manim Sideview v0.2.5 installed in VS Code on Windows.

I wonder if this is related, but whenever I press Ctrl+S when editing a non Manim file (on Windows) I get the Manim Sideview prompt to select a scene:
![image](https://user-images.githubusercontent.com/1395769/234913601-b3560d21-975c-499d-ba34-9bb3f0d1a4b8.png)

How can I stop this from appearing?
