### ISSUE TITLE
[28312] Execution returned code=0 in 7.714 seconds

### ISSUE THREAD

**Issue by NeoWangKing** [Rickaym/manim-sideview#60]
When I am trying to run any manim code, it return this massege and the preview screen does not appear. After I have tried to reinstall the extension and even VSCode, it return to being normal for a while but after some minutes, it comes to this siuation again. I don't know whether this situation is really an error or not. If so, how can I solve it?

**Comment by Rickaym** [comment]
Can you please show me the message received?
