### ISSUE TITLE
question about how to stop manim sv

### ISSUE THREAD

**Issue by morey-ow** [Rickaym/manim-sideview#61]
Thank you for making a great extension. I had a very dumb question that I cannot find an answer in the documentation and couldn't figure. How do I temporarily stop Manim SV from starting automatically - which I want it to most of the time - but sometimes I want to turn off that feature (for example if I haven't finished typing up much, or am editing a text file).

Thank you!

**Comment by Rickaym** [comment]
> Thank you for making a great extension. I had a very dumb question that I cannot find an answer in the documentation and couldn't figure. How do I temporarily stop Manim SV from starting automatically - which I want it to most of the time - but sometimes I want to turn off that feature (for example if I haven't finished typing up much, or am editing a text file).
> 
> Thank you!

If you want to stop Manim SV from rendering automatically on save, turn off [this option](https://github.com/Rickaym/manim-sideview#1-how-do-i-render-on-save).
