### ISSUE TITLE
extension does not recognize pixel_width, pixel_height properties

### ISSUE THREAD

**Issue by LucasCarvalhodaSilva** [Rickaym/manim-sideview#62]
I am rendering a video with pixel_height=1920 and pixel_width=1080 (which is not the default reselution). The output is saved by manim automatically in the directory  ../1920p60 and not in  ../1080p60.

The extension assumes the output directory is 1080p/60. 

I use this configuration settings:

`[CLI]`
`frame_rate = 60 `
`pixel_width = 1080 `
`pixel_height = 1920`

Here are some logs:

![Output](https://user-images.githubusercontent.com/55059959/234018732-5e06798c-3221-4703-9c3c-17416e8c56c1.PNG)

Is there any solution to this?

**Comment by PhilFreeman** [comment]
Able to verify above as a bug. 

If the resolution isn't specified in the config file, but the quality is, then the resolution and frame rate are defined by the quality. However if `pixel_width,` `pixel_height,` and `frame_rate` are defined in the config file (the default when using `manim init project <project name>`), then the output directory will be `{pixel_height}p{frame_rate}`, not the default quality value.

I tried to track down this bug in the source, but I don't know typescript to fix it. But, the method of relying on the `quality` key in the config file to indicate the folder name is definitely a bug. It should first try to use `pixel_height` and `frame_rate`.

**Comment by Rickaym** [comment]
This is expected behavior as the extension does not recognize--although manim itself does--the config keys `pixel_height` and `pixel_width` to determine the output quality folder.

A quick way to solve this issue is to set an obvious `video_dir` so that both the extension and manim agree on where the video is saved.

I.e.
```
[CLI]
frame_rate = 60 
pixel_width = 1080 
pixel_height = 1920
video_dir = {media_dir}/videos/{module_name}/1920p60
```

However, I will be committing a patch which will let the extension to recognize those keys for quality.

**Comment by Rickaym** [comment]
The commit e818529 addresses this issue.

**Comment by LucasCarvalhodaSilva** [comment]
> The commit [e818529](https://github.com/Rickaym/manim-sideview/commit/e818529af31c6d86288f30b17a46b3c3a7db1cf0) addresses this issue.
> 
> Edit: Released in [99bfc57](https://github.com/Rickaym/manim-sideview/commit/99bfc57f41ee5c6b84eea6bcecc3486b56660cda).

Would you mind explaining to me what to do in this situation? I still can't get the sideview to play the video.

**Comment by Rickaym** [comment]
> > The commit [e818529](https://github.com/Rickaym/manim-sideview/commit/e818529af31c6d86288f30b17a46b3c3a7db1cf0) addresses this issue.
> > Edit: Released in [99bfc57](https://github.com/Rickaym/manim-sideview/commit/99bfc57f41ee5c6b84eea6bcecc3486b56660cda).
> 
> Would you mind explaining to me what to do in this situation? I still can't get the sideview to play the video.

What is the issue? It works fine on my end.

**Comment by PhilFreeman** [comment]
Works on my end now. Can't speak for @LucasCarvalhodaSilva. Thanks!

**Comment by LucasCarvalhodaSilva** [comment]
It works, my bad!
