### ISSUE TITLE
Does not autoplay after rendering

### ISSUE THREAD

**Issue by MarkHoo** [Rickaym/manim-sideview#64]
OS: Windows10
Python：v3.9.13
vscode：v1.80.1
manim：v0.17.3， v0.16.0.post0
sideview: v0.2.5

----

Watch the video introduction on YouTube, it will play automatically after rendering. But this is not the case when I use it. Every time I need to manually click on the video to play it, it seems very troublesome.

How can I configure it so that it can play automatically after rendering. Thanks!

**Comment by Rickaym** [comment]
Hi,
You can go to `File` -> `Preferences` -> `Settings` and enable `Manim-sideview: Auto Preview`

![image](https://github.com/Rickaym/manim-sideview/assets/66440980/36a74693-4ff4-4322-81e2-b917a4761fba)

**Comment by MarkHoo** [comment]
This option is checked by default.

This problem occurs after updating the version of vscode.

After I downgraded vscode to version 1.63 today, it returned to normal.
This may be an adaptation problem between the plugin and the new version of vscode

**Comment by MarkHoo** [comment]
> 您好， 您可以进入`File`-> `Preferences`->`Settings`并启用`Manim-sideview: Auto Preview`
> 
> ![图像](https://user-images.githubusercontent.com/66440980/253732507-36a74693-4ff4-4322-81e2-b917a4761fba.png)

This option is checked by default.

This problem occurs after updating the version of vscode.

After I downgraded vscode to version 1.63 today, it returned to normal.
This may be an adaptation problem between the plugin and the new version of vscode

**Comment by MarkHoo** [comment]
> Hi, You can go to `File` -> `Preferences` -> `Settings` and enable `Manim-sideview: Auto Preview`
> 
> ![image](https://user-images.githubusercontent.com/66440980/253732507-36a74693-4ff4-4322-81e2-b917a4761fba.png)

This option is checked by default.

This problem occurs after updating the version of vscode.

After I downgraded vscode to version 1.63 today, it returned to normal.
This may be an adaptation problem between the plugin and the new version of vscode

**Comment by Rickaym** [comment]
> > Hi, You can go to `File` -> `Preferences` -> `Settings` and enable `Manim-sideview: Auto Preview`
> > ![image](https://user-images.githubusercontent.com/66440980/253732507-36a74693-4ff4-4322-81e2-b917a4761fba.png)
> 
> This option is checked by default.
> 
> This problem occurs after updating the version of vscode.
> 
> After I downgraded vscode to version 1.63 today, it returned to normal. This may be an adaptation problem between the plugin and the new version of vscode

I will look further into this and get back to you.

**Comment by gd247217** [comment]
This does have to do with the vscode version.the new version of vscode will result in this situation

**Comment by Rickaym** [comment]
This seems to be an issue due to the fact that video players need to be muted for auto-play to work, accordingly to [this post](https://developer.chrome.com/blog/autoplay-2/). Why it broke only now, I don't know.

**Comment by Rickaym** [comment]
Fixed and released as v0.2.8 [a8787f7](https://github.com/Rickaym/manim-sideview/commit/a8787f717b15a89608dc1a7183665a514d74d341)

**Comment by MarkHoo** [comment]
Thank you very much for your contribution to manim and the fix for this problem

**Comment by Rickaym** [comment]
You're welcome!
