### ISSUE TITLE
Run venv activate before running

### ISSUE THREAD

**Issue by felipefcm** [Rickaym/manim-sideview#67]
I'm having some issues importing my own packages because the extension doesn't seem to be activating the virtual env before running.
I need at least a way to tell the extension some paths to append to `sys.path`.

My workaround for this was to make a copy of `.venv/bin/manim` and manually add the paths there, and configure the extension to use that executable.

**Comment by matejaputic** [comment]
Having the same issue, except with conda

**Comment by Rickaym** [comment]
0588f831eda0fe274f79220ec4b165f6b3888378 bebdfb8b184a59ef4884826c0b7bd888e57d9374 implements this

**Comment by Rickaym** [comment]
[7ee1ca5](https://github.com/Rickaym/manim-sideview/commit/7ee1ca5e9010bf82147f1a86bc7f5ec2443ed05c)

**Comment by felipefcm** [comment]
Unfortunately having issues with the new version:
![Screenshot_20231007_202414-1](https://github.com/Rickaym/manim-sideview/assets/7122990/d0a97384-f038-48dd-948a-49008d04e5c9)

The command being run is right. All the paths too. But for some reason it gets stuck.
If I press Enter, an error is thrown mixing some paths together which is suspicious:

![Screenshot_20231007_203114](https://github.com/Rickaym/manim-sideview/assets/7122990/302ece8c-148e-4203-b31c-2410bf7bfc0a)

See how it shows `activateon`? Also the `directorype`, where `pe` comes from the path.
However, after the error, the environment is activated. I can see the (.venv) at the beginning of the line.

If I try to run the extension again, now that the environment is activated, it tries to run a weird command:
![Screenshot_20231007_203552](https://github.com/Rickaym/manim-sideview/assets/7122990/24f84288-087b-4e86-9411-38021de07089)

The `.venv/Scripts` folder doesn't exist. That's when I don't override the executable path.
If I set the extension executable path with an absolute path to the manim executable (inside `.venv/bin`), it runs the Scripts folder anyway.

Let me know if I can provide any other info about this.

**Comment by mikebarkmin** [comment]
I think this line is not correct (https://github.com/Rickaym/manim-sideview/blob/7ee1ca5e9010bf82147f1a86bc7f5ec2443ed05c/src/sideview.ts#L270) – at least for setting up a virtual env with poetry. It should be "bin" instead of "Scripts".

**Comment by Rickaym** [comment]
I have implemented mike's point on different operating systems having different virtual env folders. This should be released now with `0.2.9`. It would be great if someone can test this out and verify that it is working as intended.
