### ISSUE TITLE
Support portrait mode

### ISSUE THREAD

**Issue by mikebarkmin** [Rickaym/manim-sideview#69]
Occasionally, I want to render a YouTube Short video. For this, a need the following custom manim.cfg

```
[CLI]
pixel_width  = 1080
pixel_height = 1920
```

Unfortunately, I think there is no profile on the quality_map for this. Maybe consider adding options for portrait videos.

**Comment by Rickaym** [comment]
Is the lack of a profile associated with the extension or is it the manim framework itself?

**Comment by mikebarkmin** [comment]
I think the limitation is with this extension. Especially with the way the extension builds the output path.

**Comment by mikebarkmin** [comment]
Because the quality is assumed based on the provided pixel width and height. https://github.com/Rickaym/manim-sideview/blob/bed6141614faef6803d686247cf04d2a95f89718/src/globals.ts#L89 

For a portrait video 1080x1920 there is no key in the quality map.

**Comment by mikebarkmin** [comment]
My pull-request fixes the issue #70

**Comment by Rickaym** [comment]
Looks good to me, I will merge that and release it alongside other performance updates in the coming week.

Thanks.

**Comment by Rickaym** [comment]
Reopened to close along with the release.

**Comment by Rickaym** [comment]
[7ee1ca5](https://github.com/Rickaym/manim-sideview/commit/7ee1ca5e9010bf82147f1a86bc7f5ec2443ed05c)
