### ISSUE TITLE
command 'manim-sideview.run' not found

### ISSUE THREAD

**Issue by gd247217** [Rickaym/manim-sideview#74]
<img width="557" alt="屏幕截图 2023-10-08 155323" src="https://github.com/Rickaym/manim-sideview/assets/133908462/38dcea97-5031-434f-878d-3e2d0dced4ef">
vscode:1.63.2
python:3.9.13
manim:0.17.3
manim-sideview:0.2.6
I don’t know why the manim-sideview.run command can’t be found suddenly. It was working fine yesterday. Can I ask how to deal with this?

**Comment by Rickaym** [comment]
Hey can you please provide more information as to how you're getting this error?

**Comment by gd247217** [comment]
<img width="1080" alt="屏幕截图 2023-10-08 195753" src="https://github.com/Rickaym/manim-sideview/assets/133908462/24b3000b-64af-4ece-944d-046bc5a47e50">

This happens when you click the manim-sideview icon

<img width="1080" alt="屏幕截图 2023-10-08 200001" src="https://github.com/Rickaym/manim-sideview/assets/133908462/e6063e0c-6750-4df0-a05b-37b75bfe7e74">

**Comment by gd247217** [comment]
<img width="1080" alt="屏幕截图 2023-10-08 200508" src="https://github.com/Rickaym/manim-sideview/assets/133908462/ca2e5b0b-f900-4402-b04e-06e467e8dbd3">

When you open the command line and click manim-sideview, you will find a running error

<img width="1080" alt="屏幕截图 2023-10-08 200636" src="https://github.com/Rickaym/manim-sideview/assets/133908462/0c4baeda-2aae-4f6f-92e6-64f034d4bcd8">

**Comment by Rickaym** [comment]
Thank you.
I have identified this to be an issue with the v0.2.6 release dropping its `onCommand` activation events which are necessary for VSCode versions under 1.75.

**Comment by Rickaym** [comment]
I will release this now as v0.2.7

**Comment by gd247217** [comment]
But does upgrading vscode affect the previous question? It is a problem that the video will not play automatically. So what should I do about it?

**Comment by gd247217** [comment]
Thank you very much for taking the time to reply to me, and I look forward to the release of the new version.

**Comment by Rickaym** [comment]
> But does upgrading vscode affect the previous question? It is a problem that the video will not play automatically. So what should I do about it?

Let's try this again with the new release and if the issue persists, we can deal with it separately.

**Comment by gd247217** [comment]
I'll go experiment now and I'll give back the results later, thank you very much

**Comment by gd247217** [comment]
I tested it and no error was reported. Maybe I deleted something by mistake before.

**Comment by Rickaym** [comment]
> I tested it and no error was reported. Maybe I deleted something by mistake before.

Ah so it is all working fine?

**Comment by gd247217** [comment]
I found that although no error was reported, the video would not pop up automatically. I am still checking whether it is my configuration problem. I tried several versions, but nothing worked.

**Comment by Rickaym** [comment]
> I found that although no error was reported, the video would not pop up automatically. I am still checking whether it is my configuration problem. I tried several versions, but nothing worked.

Oh, is this a separate issue to the command not being found?

**Comment by gd247217** [comment]
The command not found problem has been solved in the new version, but the video will not pop up automatically. I feel it is my own problem. I am still dealing with it.The interface of manim-sideview video will not pop up automatically.

**Comment by Rickaym** [comment]
> The command not found problem has been solved in the new version, but the video will not pop up automatically. I feel it is my own problem. I am still dealing with it.The interface of manim-sideview video will not pop up automatically.

Can you please make a separate issue on this? Also include the logs inside the output channel you can see when you use the command `Manim: Reveal Output Channel`.

**Comment by gd247217** [comment]
Thank you very much. I found out that it was a problem with my version. It was solved when I updated to the latest versions of vscode and manim-sideview.
