### ISSUE TITLE
when add '-ql' cli args, it can't find the file

### ISSUE THREAD

**Issue by chrisyy2003** [Rickaym/manim-sideview#75]
when add '-ql' cli args, it still look for the video in 1080p

**Comment by Rickaym** [comment]
Does it work if you use a `manim.cfg` file instead with:

```
[CLI]
quality=low
```

**Comment by Rickaym** [comment]
![image](https://github.com/Rickaym/manim-sideview/assets/66440980/27f7d9a9-1627-4ba2-a5ce-6cc1967e5240)
I am not able to reproduce the issue.

**Comment by chrisyy2003** [comment]
well i do the same
<img width="1183" alt="image" src="https://github.com/Rickaym/manim-sideview/assets/63803385/c59ca54a-3484-4928-89c7-023b6498de2e">

**Comment by Rickaym** [comment]
> Does it work if you use a `manim.cfg` file instead with:
> 
> ```
> [CLI]
> quality=low
> ```
> 
> In the meanwhile, I will try to reproduce the issue on my side.

Use this solution. The ETA will be long on implementing this.

**Comment by MrDiver** [comment]
Maybe this should be documented in the README ?

**Comment by Rickaym** [comment]
> Maybe this should be documented in the README ?

Yes, I agree.
