### ISSUE TITLE
Command line quotations needed

### ISSUE THREAD

**Issue by ervinnemeth** [Rickaym/manim-sideview#78]
Hi Team,
Manim-sideview tries to run the following command on the command line:

`some path\manim some other path\scene.py CreateCircle`

It fails in cases where special characters are in the path. Like white space. The correct approach is:

`"some path\manim" "some other path\scene.py" CreateCircle`

**Comment by Rickaym** [comment]
Hey!
The command manim-sideview in the terminal only represents the command being executed in the background. Technically, manim-sideview should still work despite special characters being in a path without the quotes, but I understand the worry seeing the command in the terminal.
