### ISSUE TITLE
Commented out lines in manim.cfg are not discarded

### ISSUE THREAD

**Issue by henrikmidtiby** [Rickaym/manim-sideview#79]
There seems to be an issue with the configuration parser of manim-sideview.
During development of an animation, my `manim.cfg` file looked like this.
This worked fine.
```
[CLI]
#quality = production_quality
quality = low_quality
```
When I afterwards wanted to change the quality settings to `production_quality`, the preview kept showing the low quality version of the rendered file. At this point the configuration file looked like this.
```
[CLI]
quality = production_quality
#quality = low_quality
```
To fix the issue, I had to ensure that the active line in the config file was at the end of the file.
```
[CLI]
#quality = low_quality
quality = production_quality
```
I think that the issue is with the configuration parser (`master/src/configParser.ts`), as it does look for comments (lines starting with #) in the config file.

**Comment by lbirkert** [comment]
A solution would be to switch to a proper TOML parser which supports the entire standard instead of our minimal implementation.

https://www.npmjs.com/package/toml
