### ISSUE TITLE
The button of sideview is missing in vscode  how to configure it?

### ISSUE THREAD

**Issue by alitahri** [Rickaym/manim-sideview#84]
I followed all the steps to install Manim as shown by this video 
https://www.youtube.com/watch?v=ib-I3ayqFaw&t=3s

Unfortunately, the button of sideview is missing in vscode.
I can launch Manim programs, but the animation is done on an external media player (media player of windows)

**Comment by Rickaym** [comment]
Hey, can you please provide a screenshot of your vscode when you expect the button?

**Comment by alitahri** [comment]
Please find as attached the requested screenshot
![screenshot](https://github.com/Rickaym/manim-sideview/assets/28135631/b834458f-8988-4ee3-9524-dc9cc4cadf70)

**Comment by Rickaym** [comment]
I see. When you press F1 and type in Manim Run, can you see the command? 
On top of that, I would recommend saving your file to a folder and opening that folder on vscode.

**Comment by alitahri** [comment]
Sorry can you send me a screenshot?

**Comment by Rickaym** [comment]
![image](https://github.com/Rickaym/manim-sideview/assets/66440980/cc490b01-6caa-4deb-af11-4d86aa250917)

**Comment by alitahri** [comment]
![screen_shot2](https://github.com/Rickaym/manim-sideview/assets/28135631/530d5f07-2d42-4a73-b269-b1bcda7c0edc)

**Comment by Rickaym** [comment]
![image](https://github.com/Rickaym/manim-sideview/assets/66440980/494066b8-bc3d-42d5-9a95-01b502906ec0)
Right click on the group of buttons and make sure that manim sideview's run is selected.
