### ISSUE TITLE
When I added a video path to the file “manim.cfg”, I couldn't preview it anymore

### ISSUE THREAD

**Issue by daigemath** [Rickaym/manim-sideview#86]
When I added the following content to the file“manim.cfg”:
[CLI]
Video_dir=D: \ code \ manim \ video
Media dir={video dir}
When using Manim Sideview, there will be the following error message:
Manim Sideview: Predicted output file does not exist at'd: \ code, manim \ D: \ code \ manim \ video \ test. mp4 "Make sure that the designed video directories are reflected in the extension log."
But once I cancel the content of manim.cfg, I can preview it now

**Comment by Rickaym** [comment]
Your video dir is malformatted. Perhaps try a relative path in quotations
