### ISSUE TITLE
"Scene" is not defined

### ISSUE THREAD

**Issue by thekreindo** [Rickaym/manim-sideview#87]
Manim sideview works well, but I can't use autocompletion, classes and functions are underlined as error
![image](https://github.com/Rickaym/manim-sideview/assets/109491899/57557132-971f-4ea5-a984-c61efce28539)

**Comment by Rickaym** [comment]
Hey,
That is because your VSCode is not configured to the python environment with manim installed. You can bring up the configuration menu by clicking the second to right-most icon with 'python' in its name.

**Comment by thekreindo** [comment]
where is the menú? i can´t see the icon with python's name

**Comment by Rickaym** [comment]
Can you please show me a screenshot of your bottom bar?
