### ISSUE TITLE
The VSC extension has very annoying problems

### ISSUE THREAD

**Issue by Boris501** [Rickaym/manim-sideview#88]
1. Sometimes it gets to the point where it opens whenever i try to write code and asks me what i want to run.
2. It sometimes automatically opens that terminal when i try to write code in my scene class.

**Comment by Rickaym** [comment]
Hi,
Do you have the runOnSave setting enabled? I suspect something related to automatic running is happening.

**Comment by Boris501** [comment]
@Rickaym I have autosave on, but how do i disable runOnSave?
I think we found the problem

**Comment by Boris501** [comment]
Nevermind i kinda got it

**Comment by Rickaym** [comment]
Ah, what was the issue?
