### ISSUE TITLE
Wrong videoSrc when rendering remote code on Windows subsystems for Linux

### ISSUE THREAD

**Issue by WangQianliang** [Rickaym/Manim-Sideview#9]
I use all default settings. And the video file rendering is fine. Only the video src path is wrong.

It should be something like `https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-webview.net/......` like the final js script src. But instead, it's `https://file%2B.vscode-resource.vscode-webview.net/......`.

**Comment by Rickaym** [comment]
Can you please tell me more about your working configurations in vscode with the log that gets printed in the output?

**Comment by WangQianliang** [comment]
My working configuration is that I use vs code with `Remote-WSL` extension so that I can edit code on wsl from vscode on my windows. I use default settings for `Manim-Sideview`.

![image](https://user-images.githubusercontent.com/11132316/146662140-74972e6a-6958-48e5-b54e-15dd3519cb43.png)
![image](https://user-images.githubusercontent.com/11132316/146662233-219196e7-a6e6-4e5b-9c1e-f00c55d348da.png)

But if I change the video src manually. Everything works fine.
![image](https://user-images.githubusercontent.com/11132316/146662299-dde6aa5b-620d-4e2d-9351-164d8cb256bf.png)

**Comment by Rickaym** [comment]
090d8de9c712438471c378f8fb896b96caeefe3c 

Note: should be fixed in update 0.0.13

**Comment by Rickaym** [comment]
c9476261f4964cce7e50717b6e2e785e09a64139

Final patch.
This commit should fix the issue.
