### ISSUE TITLE
mac-: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

### ISSUE THREAD

**Issue by flutesing** [Rickaym/manim-sideview#90]
: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by Rickaym** [comment]
You need to install ffmpeg https://ffmpeg.org/
