### ISSUE TITLE
Two renders simultaneously

### ISSUE THREAD

**Issue by slevey087** [Rickaym/manim-sideview#92]
If I save the file I'm working on while it is still rendering from the previous save, _sometimes_ it will terminate the previous process and start the new one, and sometimes it will just run both of them at the same time. (I can tell because the animation numbers will be incrementing from two different places). I am not sure what triggers which behavior. Even when they run both at the same time, the earlier process still displays "Cause: An old process has been terminated due to a termination signal" once it finishes.

**Comment by Rickaym** [comment]
Interesting, what is the expected behavior here? 
The new save overrides the previous save assuming that the user would like to see the later animations sooner.

**Comment by slevey087** [comment]
I think it is definitely for the new save to stop the previously-running render immediately, then start the new one. I sometimes have renders that take several minutes to complete, and then I realize I need to change something and start over. Finishing the old render means creating a bunch of now-outdated animations, and also presumably slowing the processing considerably.

**Comment by Rickaym** [comment]
Mhm, that makes sense. I will check that manim sideview is using the manim cache system properly. That can only be the source of the slowdown, otherwise it should be on par with normal manim.

**Comment by Rickaym** [comment]
Apologies for the delay. But I'm having trouble recreating this so far.
