### ISSUE TITLE
Uncap the Sideview video or image preview resolution

### ISSUE THREAD

**Issue by h4ckt1v1st** [Rickaym/manim-sideview#93]
Even if I am rendering in 1080p, if I expand the window to full screen on my second monitor, the video only have a short resolution and rest of the screen is filled with checker pattern.
Now that I can detach the manim sideview tab from the VSCode main window, I want to make use of my other monitor to display the render in full screen.

**Comment by Rickaym** [comment]
Hey,
Can you please attach a screenshot of the case?

**Comment by h4ckt1v1st** [comment]
Hey Rick, sure.

![image](https://github.com/user-attachments/assets/300cfa47-28a3-4dd5-8881-22ac3b35b9f4)

**Comment by Rickaym** [comment]
This has been fixed and released as 0.2.15
