### ISSUE TITLE
manim side view does not pop up, Error: spawn manim ENOENT[undefined]

### ISSUE THREAD

**Issue by Emi0719** [Rickaym/manim-sideview#95]
Manim sideview was working just fine when i first install it, but then i try to tidy up my library and this error occurred. I think I might have accidentally delete something, but I don't remember what exactly i deleted.
Not sure what i did wrong here and I don't understand what the error mean. When i click the sideview button, this just popped up in the terminal, can anyone please explain to me what's going on and how to fix this? Tysm.
![Screenshot 2024-07-16 230805](https://github.com/user-attachments/assets/a7a52ea5-eae5-4871-aa1d-55d0219cf58a)

**Comment by lbirkert** [comment]
Seems more like a manim specific issue rather than an issue that is related to this extension. Can you run manim manually in your terminal? `manim "c:\Users\emily\Documents\practice\example1" Scene1`

**Comment by lbirkert** [comment]
If that does not work, you should go ahead and reinstall manim.

**Comment by Emi0719** [comment]
> If that does not work, you should go ahead and reinstall manim.

i have ran it manually and reinstalled manim too, but the error remains

**Comment by lbirkert** [comment]
> > If that does not work, you should go ahead and reinstall manim.
> 
> i have ran it manually and reinstalled manim too, but the error remains. Is there anything else i can do?

does running manually work?

**Comment by Emi0719** [comment]
no it doesnt

**Comment by Rickaym** [comment]
How did you install Manim?

**Comment by Emi0719** [comment]
i installed it by chocolatey

**Comment by Emi0719** [comment]
i'm n

> How did you install Manim? This seems like an issue of the manim executable not being on path.

i installed it by chocolatey

**Comment by Emi0719** [comment]
> > > If that does not work, you should go ahead and reinstall manim.
> > 
> > 
> > i have ran it manually and reinstalled manim too, but the error remains. Is there anything else i can do?
> 
> does running manually work?

no it doesn't work

**Comment by lbirkert** [comment]
> > > > If that does not work, you should go ahead and reinstall manim.
> > > 
> > > 
> > > i have ran it manually and reinstalled manim too, but the error remains. Is there anything else i can do?
> > 
> > 
> > does running manually work?
> 
> no it doesn't work

than you need to firstly find out how to install manim correctly, so that you can run it manually.

**Comment by lbirkert** [comment]
there should be guides on this online, you can also try to use a different installation method if you current one does not work.

**Comment by guweisen1** [comment]
What worked for me is that I am running manim in a virtual environment and so I make sure that I am running my VSCode in my virtual environment. 

Steps: 
1. Open CMD 
2. Activate your virtual environment ( .\[your virtual env]\Scripts\activate )
3. Check if manim is installed properly ( manim --version ) 
4. If it is installed then proceed to VSCode, if not install manim using pip ( pip install manim )
5. In VSCode, change your python interpreter to the virtual environment where manim was installed earlier.
6. Click on File --> Preferences --> Settings. 
7. In Settings, search manim
8. In Default Manim Path, type in your manim path 
8.a To find your manim path, in cmd that you have opened earlier type ( where manim ), copy the path and paste in Default Manim Path
9. Change the Manim Sideview to the version that you got from Step 3. 

Hopefully, this works for you!
