### ISSUE TITLE
modify resolution config does not work 

### ISSUE THREAD

**Issue by gelu110** [Rickaym/manim-sideview#96]
After modifying the resolution configuration to portrait in the code file, the side view cannot output normally, and the old code content is still output after modifying the code.
config.frame_width = 9
config.frame_height = 16
config.pixel_width = 1080
config.pixel_height = 1920

**Comment by Rickaym** [comment]
Hey, can you please elaborate on "cannot output normally"?

**Comment by moroha10085** [comment]
I am experiencing the same problem. I think it is probably due to the fact that the directory that manim sideview is looking at is 1080p60. So if there is a way to change to the directory where that resolution is stored, I think the problem will be solved.
